fun main(args: Array<String>) {
    println("Введите три целочисленных точки координатной плоскости, которые будут формировать треугольник:")
    print("x1: ")
    var x = readln().toDouble()
    print("y1: ")
    var y = readln().toDouble()
    val point1 = Point(x, y)
    print("x2: ")
    x = readln().toDouble()
    print("y2: ")
    y = readln().toDouble()
    val point2 = Point(x, y)
    print("x3: ")
    x = readln().toDouble()
    print("y3: ")
    y = readln().toDouble()
    val point3 = Point(x, y)
    val triangle = Triangle(point1, point2, point3)
    val center = triangle.findCenter()
    println("${center.x} ${center.y}\n${triangle.findRadius(center)}")
}